### ISSUE TITLE
Connecting to device not working?

### ISSUE THREAD

**Issue by WaterBug9** [roslovets/SP110E#2]
I'm not too good at python and only have a pretty basic understanding of it and this might be a dumb question but when I try to connect to my device if comes up with this error:
```
Traceback (most recent call last):
  File "c:\Users\samet\Downloads\Python Scripts\LED\test.py", line 8, in main
    await device.connect('7F:00:00:04:3C:7F')
  File "C:\Users\samet\AppData\Local\Programs\Python\Python310\lib\site-packages\sp110e\driver.py", line 46, in connect
    await self._client.connect()
  File "C:\Users\samet\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 257, in connect
    await self.get_services()
  File "C:\Users\samet\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 426, in get_services
    await self._requester.get_gatt_services_async(
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\samet\Downloads\Python Scripts\LED\test.py", line 25, in <module>
    asyncio.run(main())
  File "C:\Users\samet\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\samet\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
```

My code is only one of the example codes and the app on my phone works fine

Code:
```
from sp110e.controller_sync import ControllerSync

device = ControllerSync('7F:00:00:04:3C:7F', timeout=2, retries=1)
device.connect()
device.print_parameters()
device.switch_on()
device.set_brightness(255)
device.switch_off()
device.disconnect()
```

Please reply :)

**Comment by WaterBug9** [comment]
Also is it possible to individually address one of the LED's?

**Comment by roslovets** [comment]
> I'm not too good at python and only have a pretty basic understanding of it and this might be a dumb question but when I try to connect to my device if comes up with this error:

Your code is correct. I think sometinh wrong with your environment or BLE driver. On my WIndows laptop this does not work as well. But works ok on Raspberry Pi.

**Comment by roslovets** [comment]
> Also is it possible to individually address one of the LED's?

Unfortunately SP110E can't do that.
