### ISSUE TITLE
the change of brightness, color, and connection does not work

### ISSUE THREAD

**Issue by trc99** [roslovets/SP110E#4]
```
from sp110e.controller_sync import ControllerSync

devices = ControllerSync.discover(ControllerSync)
print(devices)
mac = devices[0]['SP110E']

device = ControllerSync(mac, timeout=2, retries=1)

device.print_parameters()

device.switch_on()
device.set_brightness(255)
device.set_color(255,0,0)
device.print_parameters()
```

result:

```
[{'SP110E': '97:79:0D:19:5F:81'}]
state : False
mode : 0
speed : 0
brightness : 0
ic_model : SM16703
sequence : RGB
pixels : 0
color : [0, 0, 0]
white : 0
Traceback (most recent call last):
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\sp110e\controller.py", line 208, in _connect_with_retries
    await self._driver.connect(self._mac, timeout=self._timeout)
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\sp110e\driver.py", line 47, in connect
    await self._client.start_notify(self.CHARACTERISTIC, self._callback_handler)
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\bleak\__init__.py", line 717, in start_notify
    await self._backend.start_notify(characteristic, wrapped_callback, **kwargs)
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\bleak\backends\winrt\client.py", line 951, in start_notify
    await winrt_char.write_client_characteristic_configuration_descriptor_async(
OSError: [WinError -2147418113] Разрушительный сбой

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\Lib\run.py", line 11, in <module>
    device.switch_on()
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\syncer.py", line 44, in run
    return asyncio.get_event_loop().run_until_complete(f(*args, **kwargs))
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\sp110e\controller_sync.py", line 41, in switch_on
    await super().switch_on()
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\sp110e\controller.py", line 46, in switch_on
    await self.set_state(True, force=force)
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\sp110e\controller.py", line 77, in set_state
    await self._connect_and_write_parameters({'state': state}, force=force)
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\sp110e\controller.py", line 221, in _connect_and_write_parameters
    await self._connect_with_retries()
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\sp110e\controller.py", line 211, in _connect_with_retries
    raise Exception
Exception
```

how can i fix it

**Comment by trc99** [comment]
device.connect() does nothing, stops the code with an error

output:
```
None
state : False
mode : 0
speed : 0
brightness : 0
ic_model : SM16703
sequence : RGB
pixels : 0
color : [0, 0, 0]
white : 0
False
Traceback (most recent call last):
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\sp110e\controller.py", line 208, in _connect_with_retries
    await self._driver.connect(self._mac, timeout=self._timeout)
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\sp110e\driver.py", line 44, in connect
    raise BleakError(f'A device with address {mac_address} could not be found')
bleak.exc.BleakError: A device with address 97:79:0D:19:5F:81 could not be found
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\Lib\run.py", line 12, in <module>
    device.connect()
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\syncer.py", line 44, in run
    return asyncio.get_event_loop().run_until_complete(f(*args, **kwargs))
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\sp110e\controller_sync.py", line 28, in connect
    await super().connect()
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\sp110e\controller.py", line 29, in connect
    await self._connect_with_retries()
  File "C:\Users\Администратор\Desktop\ворки\controller_led_lib_test\lib\site-packages\sp110e\controller.py", line 211, in _connect_with_retries
    raise Exception
Exception

Process finished with exit code 1
```
pls help

**Comment by popy2k14** [comment]
Same issue here, any updates on this?

**Comment by trc99** [comment]
> Same issue here, any updates on this?

I gave up on this a long time ago

**Comment by popy2k14** [comment]
thx, for the update.
It seems winrt related but sadly, beyond my knowledge.
